package lib.events;

public enum EventType 
{
	PAPER_SELECTED, 
	ADD_RELEVANT_PAPER, 

	PAPER_BASE_IMPORT_PAPERS, 
	PAPER_BASE_PAPERS_FILTERED, 
	PAPER_BASE_UPDATE_PAPER_LIST, 
	PAPER_BASE_PAPER_UPDATE_COMPLETE
}
